spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4GEyYwm5rAgD2Hqnh8tK
      secret-key: jokudFCkaJAurhBZQ63FCvzoV5EaZY
      oss:
        bucket: wch-mall
        endpoint: oss-cn-shenzhen.aliyuncs.com

  application:
    name: mall-third-party

server:
  port: 30000
